export default {
  translation: {
    double: 'Rss already exists',
    url: 'Must be valid url',
    404: 'This source doesn\'t contain valid rss',
    updateError: 'Data update failed',
    default: 'Something went wrong...',
    processing: 'adding RSS...',
    filling: 'RSS has been loaded',
    mainTitle: 'RSS Reader',
    promo: 'Start reading RSS today! It is easy, it is nicely.',
    placeholder: 'RSS link',
    example: 'Example: https://ru.hexlet.io/lessons.rss',
    copyright: 'designed by me',
    addButton: 'Add',
    Preview: 'Preview',
    Posts: 'Posts',
    Feeds: 'Feeds',
  },
};
